name: Update Time

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch time from World Time API
      run: |
        TIME=$(curl -s "https://worldtimeapi.org/api/timezone/Asia/Kolkata" | jq -r .datetime)
        echo "export const API_TIME = '$TIME';" > time.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
